= OpenShift Notes and Commentary

This repository includes OpenShift related notes, scripts and so on. 

The main purpose of this repository is to provide helpers to install OpenShift in on-premise environment.

* link:install/[install]-directory includes instructions and scripts to install OpenShift in online or airgapped environments.
* link:operation/[operation]-directory includes instructions and scripts related to configuring/operating OpenShift.

== Architecture

.OpenShift architecture
image::images/OpenShift_architecture.svg[]

The architecture of OpenShift in the context of this repository. Just a few comments about it:

* Architecture shows an airgapped environment, but it can be made online environment by adding a gateway from internal OCP network to network with external access.
* Jump server is the one used to download OpenShift images and other software.
** Files from jump server are transferred to bastion.
* Bastion server is the one that is used to install/manage OpenShift environment.
* Bastion also includes all supporting services like DHCP.
** All the services could be in dedicated servers, if so desired.
* Load balancer is HAProxy in this environment.
** Some other load balancer can be also used.
** Load balancer external host name(s) must be accessible from OpenShift internal network.
* LDAP and NFS in bastion are used in this environment to provide those services.
** In real life, LDAP would be enterprise LDAP somewhere and NFS would be a typical enterprise storage solution.
** Or storage could be https://www.openshift.com/products/container-storage/[Red Hat OpenShift Container Storage].
* Two worker nodes are labeled so that ingress router will run on those nodes.
* link:images/OCP_typical_VMWare.png[Typical architecture in VMWare ]
