FROM alpine-base

#inspired by https://github.com/cturra/docker-ntp

#chrony configuration
COPY ./chrony.conf /etc/chrony/chrony.conf

# ntp port
EXPOSE 123/udp

# start chronyd in the foreground
CMD [ "/usr/sbin/chronyd","-d", "-s" ]
