#DNS container image for OpenShift
FROM alpine-base

ARG OCP_DOMAIN

COPY named.conf /etc/bind/named.conf
COPY ${OCP_DOMAIN}.zone /var/bind/

EXPOSE 53 53/udp

CMD ["/usr/sbin/named","-g"]
#CMD ["/bin/sh"]
