FROM alpine-base
#heavily inspired by https://github.com/instantlinux/docker-tools/tree/master/images/dhcpd-dns-pxe



ARG OCP_DHCP_NETWORK_INTERFACE
ENV OCP_DHCP_NETWORK_INTERFACE=${OCP_DHCP_NETWORK_INTERFACE}
#if ENABLE_LOG is true, dhcpd and tftp logs to standard out/err
ENV ENABLE_LOG true


#copy pxe files
WORKDIR /usr/share/syslinux/pxelinux.cfg
COPY ./pxelinux .

#dhcp
WORKDIR /
COPY dhcpd.conf /etc/dhcp/dhcpd.conf
COPY start_dhcp_pxe.sh /
EXPOSE 67/udp 69/udp

CMD ["/bin/sh","/start_dhcp_pxe.sh"]
#CMD ["/bin/sh"]
