= OpenShift installation on installer-provisioned infrastructure - online
:toc: left
:toc-title: Table of Contents

This directory includes scripts to install OpenShift on installer-provisioned infrastructure in online environment. 

VSphere is the platform of choice and https://docs.openshift.com/container-platform/4.6/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html[IPI install is well documented]. Everything here is based on that documentation.

The idea behind this repo and these scripts is to provide quick install of OpenShift with minimal external dependencies.

The helper script link:omg-ipi.sh[omg-ipi.sh] has commands to setup DNS, DHCP, Load balancer and others that support OpenShift and enable quick install with minimal external dependencies.

== Requirements

* VCenter access. Administrator privileges (or https://docs.openshift.com/container-platform/4.6/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html#installation-vsphere-installer-infra-requirements_installing-vsphere-installer-provisioned-customizations[mandatory set of privileges])
* Enough resources in VMWare to install OpenShift and any workloads on top of it.
* Bastion host, preferrably a RHEL-based Linux server. 
** Installation (and administration) is done from this bastion.
* Internet access.

== Prepare

Before installing OpenShift, prepare yourself.

* Login to bastion as root.
* Clone or download this repo.
* https://console.redhat.com/openshift/downloads[Download _pull-secret.json_ from Red Hat].
* Set environment variables in link:ipi_environment.sh[ipi_environment.sh]
** Variables include VSphere configuration, DHCP and network configuration, and others.
** Be mindful and set all relevant variables.
** Source variables: `source ipi_environment.sh`
* Execute helper script,`sh omg-ipi.sh`, to see help.

== Install tools and clients

* Install prereq packages (like DHCP) and useful tools:
** `sh omg-ipi.sh install-prereqs`
* Download and install required clients/tools like _oc_, _openshift-install_, _coredns_, etc.:
** `sh omg-ipi.sh download-clients`

== Setup services

OpenShift requires services DHCP, DNS, NTP. Load balancer is good to have.

You need to have required services configured, up and running before installing OpenShift. All services can be set up on bastion, if you don't have or don't want to use external services.

=== NTP

* Setup bastion as NTP server:
** `sh omg-ipi.sh setup-ntp`

=== DNS

* Setup bastion as DNS server:
** `sh omg-ipi.sh setup-dns`

OpenShift domains are added to DNS as well as additional hosts specified _OCP_OTHER_DNS_HOSTS_ environment variable.
There is _DNS_FORWARDERS_ environment variable that should have any external DNS addresses. The command also configures bastion to use local DNS.

DNS is https://coredns.io/[CoreDNS] and configured as systemd service (`systemctl status coredns`).

Configuration is in _/etc/coredns/_ directory.

=== DHCP

* Setup bastion as DHCP server:
** `sh omg-ipi.sh setup-dhcp`

DHCP is configured as specified in environment variables and dynamically gives IP addresses to OpenShift nodes.

DHCP is configured as systemd service (`systemctl status dhcpd`).

Configuration is in file _/etc/dhcp/dhcpd.conf_.

=== Load balancer

* Setup bastion as load balancer:
** `sh omg-ipi.sh setup-lb`

Load balancer is configured to forward requests to OpenShift API and apps endpoints to virtual IP addresses specified by _OCP_VSPHERE_VIRTUAL_IP_API_ and _OCP_VSPHERE_VIRTUAL_IP_INGRESS_ environment variables.

Load balancer is http://gobetween.io/[gobetween].

Gobetween is configured as systemd service (`systemctl status gobetween`).

Configuration is in file _/etc/gobetween/config.toml_.

==== Load balancer distribution

If you use another host as load balancer, you can create load balancer distribution file and copy/move it load balancer host.

* Create load balancer distribution:
** `sh omg-ipi.sh create-lb-dist-package`
** Gobetween binary, environment variable file, and scripts are added to _dist-lb.tar_ file.
* Move/copy _dist-lb.tar_ to load balancer.
* Extract tar using:
** `tar -P -xf dist-lb.tar`
** Note: -P option is important.
* Verify that environment variables are correct in link:ipi-environment.sh[ipi-environment.sh].
* Configure and start Gobetween load balancer:
** `sh setup-lb.sh`

=== Firewall and VCenter certificates

Before installing OpenShift, open required ports in Bastion and download VCenter certificates:

* `sh omg-ipi.sh firewall open`
* `sh omg-ipi.sh extract-certs`

== Install OpenShift

OpenShift installation uses _openshift-install_-command and installation uses configuration given as environment variables in link:ipi_environment.sh[ipi_environment.sh].

* Start install:
** `sh omg-ipi.sh create`
* Follow installation from consolr and/or VCenter.
** Use `sh omg-ipi.sh ocp-cluster-operators` in another terminal to see cluster operator status.
* Wait until installation is complete.
* When installation is complete, this kind of output is printed:
```
DEBUG Cluster is initialized
INFO Waiting up to 10m0s for the openshift-console route to be created...
DEBUG Route found in openshift-console namespace: console
DEBUG Route found in openshift-console namespace: downloads
DEBUG OpenShift console route is created
INFO Install complete!
INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/root/ocp-ipi-install/auth/kubeconfig'
INFO Access the OpenShift web-console here: https://console-openshift-console.apps.ocp07.forum.fi.ibm.com
INFO Login to the console with user: "kubeadmin", and password: "oc4dL-5nmQY-GbvAB-KrVSI"
DEBUG Time elapsed per stage:
DEBUG     Infrastructure: 1m5s
DEBUG Bootstrap Complete: 18m51s
DEBUG                API: 2m57s
DEBUG  Bootstrap Destroy: 23s
DEBUG  Cluster Operators: 19m20s
INFO Time elapsed: 41m24s
```
* Make note of console URL, user and password.
* OpenShift is ready to be used.
** If OpenShift is not used, destroy it using:
** `sh omg-ipi.sh destroy`
