= OpenShift installation on user-provisioned infrastructure
:toc: left
:toc-title: Table of Contents

This directory includes scripts to install OpenShift on user-provisioned infrastructure in online environment or airgapped environment.

* Supporting services NTP, Apache, DNS, DHCP & PXE and HAProxu are installed on bastion-server.
** Services can be installed on other servers as well.
* link:environment.sh[environment.sh] includes environment variables related to installation.
* link:omg.sh[omg.sh] is the main script to use to install OpenShift.

== Assumptions

=== Online environment

* Bastion is fresh RHEL installation (for example, 8.2).
* Bastion has two network interfaces, "external" and "internal".
** "external" network is the one that users use to access OpenShift.
** "internal" network is the one where OpenShift nodes are installed.
* OpenShift nodes are available. 
** For example: virtual machines have been created (no OS installed).

=== Airgapped environment

* Jump-server with access to Internet is fresh RHEL installation (for example, 8.2).
* Bastion is fresh RHEL installation (for example, 8.2).
* HAProxy is used as load balancer and it is fresh RHEL installation (for example, 8.2).
* RHEL must be the same version in both jump-, bastion- and haproxy-servers.
* Bastion is located in the same network as OpenShift nodes.
* HAProxy-server has two network interfaces, "external" and "internal".
** "external" network is the one that users use to access OpenShift.
** "internal" network is the one where OpenShift nodes are installed.
* OpenShift nodes are available. 
** For example: virtual machines have been created (no OS installed).

*IMPORTANT*: jump-server,bastion-server and haproxy-server must be identical installations. For example, all have been installed from the same ISO-image. This is because prereq packages (such as Apache and DNS) are packaged in jump-server as a local repository which is then transferred to bastion-server. Repository does not include packages already available in jump-server, so the same packages must be available also in bastion-server and haproxy-server.

== Prepare for installation

=== Online environment

* Copy/clone/otherwise transfer this directory to bastion-server.
* Download _pull-secret.json_ from Red Hat.
* Open link:environment.sh[environment.sh] and set variables to match your environment.
** Check desired OpenShift version from https://mirror.openshift.com/pub/openshift-v4/clients/ocp/.
** Check desired RHCOS version from https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/.
* Source variables:
** ´source environment.sh`
* See available commands in link:omg.sh[omg.sh]:
** `sh omg.sh`
* Setup bastion-server by using commands below. All at once or one at a time.
```
sh omg.sh install-prereqs
sh omg.sh download-clients
sh omg.sh setup-ntp
sh omg.sh setup-apache
sh omg.sh setup-dns
sh omg.sh setup-dhcp
sh omg.sh setup-haproxy
sh omg.sh firewall-open
```
* Online-installation installs HAProxy to bastion-server. HAProxy can be installed on separate server by copying this directory to HAProxy-server and setting HAProxy there.

=== Airgapped environment

* Copy/clone/otherwise transfer this directory to jump-server.
* Download _pull-secret.json_ from Red Hat.
* Open link:environment.sh[environment.sh] and set variables to match your environment.
** Check desired OpenShift version from https://mirror.openshift.com/pub/openshift-v4/clients/ocp/.
** Check desired RHCOS version from https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/.
* Source variables:
** ´source environment.sh`
* See available commands in link:omg.sh[omg.sh]:
** `sh omg.sh`
* Setup jump-server by using commands below. All at once or one at a time.
```
sh omg.sh install-prereqs
sh omg.sh download-clients
sh omg.sh create-certs
sh omg.sh create-mirror-registry
sh omg.sh do-mirroring
sh omg.sh create-dist-package
```
* The last commands creates following files:
** _dist.tar_
** _rhcos.tar_
** _mirror-registry.tar_
* Transfer the files to bastion-server to _/root_-directory.
* Login to bastion-server as root.
* Extract tar-packages using following commands:
```
tar -xf dist.tar
tar -P -xf rhcos.tar
tar -P -xf mirror-registry.tar
```
* Change to _dist_-directory.
* Open link:environment.sh[environment.sh] and set variables to match your environment.
** Set bastion, node IP addresses, DHCP settings etc.
* Prepare airgapped-bastion:
** `sh omg.sh prepare-bastion`
** This configures local repository and installs prereqs.
* Setup bastion-server by using commands below. All at once or one at a time.
```
sh omg.sh setup-ntp
sh omg.sh setup-apache
sh omg.sh setup-dns
sh omg.sh setup-dhcp
sh omg.sh firewall-open
```
* Create distribution package for haproxy-server:
** `sh omg.sh create-haproxy-dist-pkg`
* The command creates following files:
** _dist_haproxy.tar_
* Transfer the file to haproxy-server to _/root_-directory.
* Extract the file:
** `tar -xf dist_haproxy.tar`
* Source variables:
** ´source environment.sh`
* Execute commands:
```
sh omg.sh setup-haproxy
sh omg.sh firewall-open
```

== OpenShift installation

* Login to bastion-server.
* As root-user, execute:
** `sh omg.sh setup-openshift-install`
* Login as ocp-user to bastion-server and go to _install_-directory.
* Boot bootstrap-node and wait until it is ready.
** Verify access using ocp-user and `ssh core@bootstrap`.
* Boot master-nodes.
** Verify that you can access them.
* When all master nodes are up and running, execute:
** `openshift-install --dir=./ wait-for bootstrap-complete --log-level debug`
** Wait for results...
** After a while you should see output like:
```
    DEBUG OpenShift Installer 4.6.8
    DEBUG Built from commit f5ba6239853f0904704c04d8b1c04c78172f1141
    INFO Waiting up to 20m0s for the Kubernetes API at https://api.cluster2.forum.fi.ibm.com:6443...
    INFO API v1.19.0+7070803 up
    INFO Waiting up to 30m0s for bootstrapping to complete...
    DEBUG Bootstrap status: complete
    INFO It is now safe to remove the bootstrap resources
    DEBUG Time elapsed per stage:
    DEBUG Bootstrap Complete: 18m53s
    INFO Time elapsed: 18m53s
```
* Note the last lines, it should indicate success.
* As instructed, remove bootstrap-node:
** Login as root to haproxy-server.
** Open link:environment.sh[environment.sh] and set `OCP_NODE_HAPROXY_ADD_BOOTSTRAP=no`.
** Source variables:
** ´source environment.sh`
** Execute:
** `sh omg.sh setup-haproxy`

OpenShift can now be accessed. However, it will not be ready until all cluster operators are ready.

* As _ocp_-user, export kubeadmin-credentials:
** `export KUBECONFIG=/home/ocp/install/auth/kubeconfig`
* Verify that you can access OpenShift:
** `oc whoami`
** `oc get nodes`
* Add at least two worker nodes to complete installation.
** Make sure that worker node information is in _environment.sh_ and that DNS and DHCP services include that information.
** Start the node, it should get IP address from DHCP and register itself as worker.
* When adding worker nodes, certificate requests need to be approved before node becomes part of the cluster:
** Two CSRs per worker node must be approved.
** See certificate requests:
** `oc get csr`
** If any request in in 'Pending'-state, approve them:
** `oc adm certificate approve <csr name>`
** Approve all pending certificate requests using command:
*** `oc get csr |grep Pending |awk '{print "oc adm certificate approve " $1}' |sh`
* View node status using command:
** `oc get nodes`
* When worker nodes are ready, it takes a few moments to get everything ready.
** Use: `oc get clusteroperators` to get status of cluster operators.
** All must be available. Example output:
```
    NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE
    authentication                             4.6.8     True        False         False      19s
    cloud-credential                           4.6.8     True        False         False      43m
    cluster-autoscaler                         4.6.8     True        False         False      30m
    config-operator                            4.6.8     True        False         False      32m
    console                                    4.6.8     True        False         False      6m4s
    csi-snapshot-controller                    4.6.8     True        False         False      32m
    dns                                        4.6.8     True        False         False      29m
    etcd                                       4.6.8     True        False         False      21m
    image-registry                             4.6.8     True        False         False      11m
    ingress                                    4.6.8     True        False         False      11m
    insights                                   4.6.8     True        False         False      32m
    kube-apiserver                             4.6.8     True        False         False      13m
    kube-controller-manager                    4.6.8     True        False         False      29m
    kube-scheduler                             4.6.8     True        False         False      28m
    kube-storage-version-migrator              4.6.8     True        False         False      30m
    machine-api                                4.6.8     True        False         False      29m
    machine-approver                           4.6.8     True        False         False      30m
    machine-config                             4.6.8     True        False         False      29m
    marketplace                                4.6.8     True        False         False      30m
    monitoring                                 4.6.8     True        False         False      6m24s
    network                                    4.6.8     True        False         False      33m
    node-tuning                                4.6.8     True        False         False      32m
    openshift-apiserver                        4.6.8     True        False         False      12m
    openshift-controller-manager               4.6.8     True        False         False      30m
    openshift-samples                          4.6.8     True        False         False      12m
    operator-lifecycle-manager                 4.6.8     True        False         False      29m
    operator-lifecycle-manager-catalog         4.6.8     True        False         False      29m
    operator-lifecycle-manager-packageserver   4.6.8     True        False         False      18m
    service-ca                                 4.6.8     True        False         False      32m
    storage                                    4.6.8     True        False         False      32m
```

We can complete the installation.

* As _ocp_-user, go to _install_-directory and execute:
** `openshift-install --dir=./ wait-for install-complete`
* Output is similar to:
```
    INFO Waiting up to 40m0s for the cluster at https://api.cluster2.forum.fi.ibm.com:6443 to initialize...
    INFO Waiting up to 10m0s for the openshift-console route to be created...
    INFO Install complete!
    INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/home/ocp/install/auth/kubeconfig'
    INFO Access the OpenShift web-console here: https://console-openshift-console.apps.cluster2.forum.fi.ibm.com
    INFO Login to the console with user: "kubeadmin", and password: "mZDAZ-dYaCR-xreLR-qsC4U"
    INFO Time elapsed: 1m41s
```
* Note the web-console URL and _kubeadmin_ password.

OpenShift is now installed.


