#Alpine base image for OCP services DNS, etc
#Alpine base adds required software so that new images (dns, dhcp, etc) can be created in bastion server without access to Internet
FROM alpine:3.12.1

RUN apk add --no-cache --update bind dhcp dnsmasq syslinux chrony apache2

COPY configure.sh .
RUN sh configure.sh

CMD ["/bin/sh"]
