#Apache container image for OpenShift ignition files
FROM alpine-base

#copy ignition files
COPY *.ign /var/www/apache/

EXPOSE 80

#start Apache in foreground
CMD ["/usr/sbin/httpd","-DFOREGROUND"]
#CMD ["/bin/sh"]
