#Apache container image for RHCOS binaries
FROM alpine-base

ARG OCP_RELEASE
ARG OCP_VERSION

#Copy download script
COPY download_rhcos_binaries.sh .

#download RHCOS images to /var/www/html
RUN sh download_rhcos_binaries.sh ${OCP_RELEASE} ${OCP_VERSION} kernel
RUN sh download_rhcos_binaries.sh ${OCP_RELEASE} ${OCP_VERSION} initramfs
RUN sh download_rhcos_binaries.sh ${OCP_RELEASE} ${OCP_VERSION} rootfs

EXPOSE 80

#start Apache in foreground
CMD ["/usr/sbin/httpd","-DFOREGROUND"]
#CMD ["/bin/sh"]
