= Online and native install

Scripts to install OpenShift in online environment using native services for NTP, Apache, DHCP & PXE, DNS and HAProxy.

* NTP, Apache, DNS, DHCP & PXE and HAProxy are all installed on bastion-server.
* link:environment.sh[environment.sh] includes environment variables related to online-native install.
* link:omg-n.sh[omg-n.sh] is the main script to use to install OpenShift.

== Installation

Assumptions:

* Bastion is fresh RHEL 8.3 installation.
* Bastion has two network interfaces, "external" and "internal"
** "internal" network is the one where OpenShift nodes are installed.
* OpenShift nodes are available. 
** For example: virtual machines have been created (no OS installed).

Installation steps:

* Copy/clone/otherwise transfer _install-native_-directory to bastion server.
* Download _pull-secret.json_ from Red Hat.
* Open link:environment.sh[environment.sh] and set variables to match your environment.
** Check desired OpenShift version from https://mirror.openshift.com/pub/openshift-v4/clients/ocp/.
** Check desired RHCOS version from https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/.
* Source variables:
** ´source environment.sh`
* See available commands in link:omg-n.sh[omg-n.sh]:
** `sh omg-n.sh`
* Setup everything by using commands below. All at once or one at a time.
```
sh omg-n.sh install-prereqs
sh omg-n.sh setup-ntp
sh omg-n.sh setup-apache
sh omg-n.sh setup-dns
sh omg-n.sh setup-dhcp
sh omg-n.sh setup-haproxy
sh omg-n.sh firewall-open
sh omg-n.sh download-clients
sh omg-n.sh setup-openshift-install

```
* Login as ocp-user to bastion-server and go to _install_-directory.
* Boot bootstrap-node and wait until it is ready.
** Verify access using ocp-user and `ssh core@bootstrap`.
* Boot master-nodes.
** Verify that you can access them.
* When all master nodes are up and running, execute:
** `openshift-install --dir=./ wait-for bootstrap-complete --log-level debug`
** Wait for results...
** After a while you should see output like:
```
    DEBUG OpenShift Installer 4.6.8
    DEBUG Built from commit f5ba6239853f0904704c04d8b1c04c78172f1141
    INFO Waiting up to 20m0s for the Kubernetes API at https://api.cluster2.forum.fi.ibm.com:6443...
    INFO API v1.19.0+7070803 up
    INFO Waiting up to 30m0s for bootstrapping to complete...
    DEBUG Bootstrap status: complete
    INFO It is now safe to remove the bootstrap resources
    DEBUG Time elapsed per stage:
    DEBUG Bootstrap Complete: 18m53s
    INFO Time elapsed: 18m53s
```
* Note the last lines, it should indicate success.
* As instructed, remove bootstrap-node:
** Login as root.
** Open link:environment.sh[environment.sh] and set `OCP_NODE_HAPROXY_ADD_BOOTSTRAP=no`.
** Source variables:
** ´source environment.sh`
** Execute:
** `sh omg-n.sh setup-haproxy`

OpenShift can now be accessed. However, it will not be ready until all cluster operators are ready.

* As _ocp_-user, export kubeadmin-credentials:
** `export KUBECONFIG=/home/ocp/install/auth/kubeconfig`
* Verify that you can access OpenShift:
** `oc whoami`
** `oc get nodes`
* Add at least two worker nodes to complete installation.
** Make sure that worker node information is in _environment.sh_ and that DNS and DHCP services include that information.
** Start the node, it should get IP address from DHCP and register itself as worker.
* When adding worker nodes, certificate requests need to be approved before node becomes part of the cluster:
** Two CSRs per worker node must be approved.
** See certificate requests:
** `oc get csr`
** If any request in in 'Pending'-state, approve them:
** `oc adm certificate approve <csr name>`
* View node status using command:
** `oc get nodes`
* When worker nodes are ready, it takes a few moments to get everything ready.
** Use: `oc get clusteroperators` to get status of cluster operators.
** All must be available. Example output:
```
    NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE
    authentication                             4.6.8     True        False         False      19s
    cloud-credential                           4.6.8     True        False         False      43m
    cluster-autoscaler                         4.6.8     True        False         False      30m
    config-operator                            4.6.8     True        False         False      32m
    console                                    4.6.8     True        False         False      6m4s
    csi-snapshot-controller                    4.6.8     True        False         False      32m
    dns                                        4.6.8     True        False         False      29m
    etcd                                       4.6.8     True        False         False      21m
    image-registry                             4.6.8     True        False         False      11m
    ingress                                    4.6.8     True        False         False      11m
    insights                                   4.6.8     True        False         False      32m
    kube-apiserver                             4.6.8     True        False         False      13m
    kube-controller-manager                    4.6.8     True        False         False      29m
    kube-scheduler                             4.6.8     True        False         False      28m
    kube-storage-version-migrator              4.6.8     True        False         False      30m
    machine-api                                4.6.8     True        False         False      29m
    machine-approver                           4.6.8     True        False         False      30m
    machine-config                             4.6.8     True        False         False      29m
    marketplace                                4.6.8     True        False         False      30m
    monitoring                                 4.6.8     True        False         False      6m24s
    network                                    4.6.8     True        False         False      33m
    node-tuning                                4.6.8     True        False         False      32m
    openshift-apiserver                        4.6.8     True        False         False      12m
    openshift-controller-manager               4.6.8     True        False         False      30m
    openshift-samples                          4.6.8     True        False         False      12m
    operator-lifecycle-manager                 4.6.8     True        False         False      29m
    operator-lifecycle-manager-catalog         4.6.8     True        False         False      29m
    operator-lifecycle-manager-packageserver   4.6.8     True        False         False      18m
    service-ca                                 4.6.8     True        False         False      32m
    storage                                    4.6.8     True        False         False      32m
```

We can complete the installation.

* As _ocp_-user, go to _install_-directory and execute:
** `openshift-install --dir=./ wait-for install-complete`
* Output is similar to:
```
    INFO Waiting up to 40m0s for the cluster at https://api.cluster2.forum.fi.ibm.com:6443 to initialize...
    INFO Waiting up to 10m0s for the openshift-console route to be created...
    INFO Install complete!
    INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/home/ocp/install/auth/kubeconfig'
    INFO Access the OpenShift web-console here: https://console-openshift-console.apps.cluster2.forum.fi.ibm.com
    INFO Login to the console with user: "kubeadmin", and password: "mZDAZ-dYaCR-xreLR-qsC4U"
    INFO Time elapsed: 1m41s
```
* Note the web-console URL and _kubeadmin_ password.

OpenShift is now installed.


